### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by pdemil** [janjongboom/mbed-vscode-generator#3]
Hi,

An error occurred and is solved, see below.

```
(mbed CLI) ~/mbed-os-example-lorawan $ mbed-vscode-generator -m DISCO_L072CZ_LRWAN1
Mbed VSCode generator, v1.0.2

Verifying dependencies:
    ✔ Mbed CLI installed
    ✔ Input directory exists
    ✔ Compiler found (/Applications/MBEDCLI.app/Contents/Resources/gcc/gcc-arm-none-eabi-6-2017-q2-update/bin/arm-none-eabi-gcc)
    ✔ Debugger found (/Applications/MBEDCLI.app/Contents/Resources/miniconda/bin/pyocd-gdbserver)
    ✔ Target configured (DISCO_L072CZ_LRWAN1)

Input directory is "/Users/snapTonic/mbed-os-example-lorawan"
Output directory is "/Users/snapTonic/mbed-os-example-lorawan/.vscode"

Generating .vscode directory:
    ✔ Exporting succeeded
    ✔ Extracting include paths (269 items)
    ✔ Extracting defines (355 items)
    ✔ Loading existing c_cpp_properties.json
    ✔ Creating c_cpp_properties.json
    ✔ Loading existing tasks.json
An error occured when generating the .vscode directory TypeError: Cannot read property 'filter' of undefined
    at /usr/local/lib/node_modules/mbed-vscode-generator/cli.js:265:32
    at Object.<anonymous> (/usr/local/lib/node_modules/mbed-vscode-generator/cli.js:484:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

```

It was solved by removing the .vscode folder that was generated by the standard mbed exporter, which is not the best exporter, being the reason I wanted to try this mbed-vscode-generator :-)

**Comment by janjongboom** [comment]
@pdemil Thanks for reporting! Pushed v1.0.3 that fixes this bug.
